name: v_chat_input_ui
description: v chat text input ui and recorder this item is part of v_chat_sdk and it can be used as a standalone package
version: 1.2.0
homepage: https://v-chat-sdk.github.io/vchat-v2-docs/docs/intro
issue_tracker: https://github.com/v-chat-sdk/v_chat_input_ui/issues
repository: https://github.com/v-chat-sdk/v_chat_input_ui

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  stop_watch_timer: ^2.0.0
  place_picker: ^0.10.0
  #  google_maps_place_picker_mb: ^3.0.1
  latlong2: ^0.9.0
  super_up_core:
    path: ../../packages/super_up_core
  cross_file: ^0.3.3+4
  record: ^4.4.4
  v_chat_mention_controller: ^1.0.0
  audio_waveforms: ^1.0.4
  emoji_picker_flutter: ^1.6.1
  meta: ^1.9.1
  intl: ^0.18.0
  google_maps_flutter: ^2.3.1
  v_platform: ^1.2.0
  cached_network_image: ^3.2.3
  adaptive_dialog: ^1.9.0-no-macos.2
  textless: ^6.6.6
  phosphor_flutter: ^1.4.0
  file_picker: ^5.2.6
  image_cropper: ^4.0.1
  wechat_camera_picker: ^3.8.0
  uuid: ^3.0.7
  path_provider: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lints: ^2.1.0

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
