name: v_chat_input_ui
description: v chat text input ui and recorder this item is part of v_chat_sdk and it can be used as a standalone package
version: 1.3.0
homepage: https://v-chat-sdk.github.io/vchat-v2-docs/docs/intro
issue_tracker: https://github.com/v-chat-sdk/v_chat_input_ui/issues
repository: https://github.com/v-chat-sdk/v_chat_input_ui

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  stop_watch_timer: ^3.0.2
  place_picker_v2: ^0.0.1
  google_maps_flutter: ^2.5.0

  cross_file: ^0.3.3+4
  record: ^5.0.1
  v_chat_mention_controller: ^1.0.0
  audio_waveforms: ^1.0.4
  emoji_picker_flutter: 1.6.1
  meta: ^1.9.1
  intl: ^0.18.0
  v_platform: ^1.2.1
  cached_network_image: ^3.3.0
  adaptive_dialog: ^2.0.0
  textless: ^6.6.6
  phosphor_flutter: ^1.4.0
  file_picker: ^6.0.0
  image_cropper: ^5.0.0
  wechat_camera_picker: ^4.2.0-dev.2
  uuid: ^3.0.7
  path_provider: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  lints: ^2.1.1

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
